# Generated by Django 4.2.4 on 2023-09-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_coursetable_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtopics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtpoicsName", models.CharField(max_length=200)),
                ("subtopicDescription", models.TextField()),
                (
                    "topicid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.course"
                    ),
                ),
            ],
        ),
    ]
