# Generated by Django 4.2.4 on 2023-09-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_subtopics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtpoicsName", models.CharField(max_length=200)),
                ("subtopicDescription", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="topicName",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name="Subtopics",
        ),
        migrations.AddField(
            model_name="subtopic",
            name="topicid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
