# Generated by Django 4.2.4 on 2023-09-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subtopic_alter_course_topicname_delete_subtopics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
