# Generated by Django 4.2.4 on 2024-01-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_subtpoicsname_subtopic_subtopicsname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="subtopicsName",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
