# Generated by Django 4.2.4 on 2024-01-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_subtopic_subtopicsname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="topicid",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
