# Generated by Django 4.2.4 on 2024-01-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_subtopic_topicid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="topicid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.course",
            ),
        ),
    ]
