# Generated by Django 4.2.4 on 2024-01-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_subtopic_topicid"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertakecourse",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="topicid",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
