# Generated by Django 4.2.4 on 2024-01-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_usertakecourse_verified_alter_subtopic_topicid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="subtopicsName",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="topicid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.course"
            ),
        ),
    ]
