# Generated by Django 4.2.4 on 2024-01-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_subtopic_subtopicsname_alter_subtopic_topicid"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
